---
build_instance_type: t2.medium
launch_instance_type: t2.large
ami_type: amazonlinux
region: ap-southeast-2
build_zone: ap-southeast-2a
keypair:
build_subnet:
build_security_group:
launch_security_group:
elb_security_group_id:
device_name: /dev/xvda
device_type: gp2
volume_size: 20
delete_on_termination: true
asg_subnet_a:
asg_subnet_b:
elb_subnet_a:
elb_subnet_b:
elb_health_check: /healthcheck
elb_health_check_port: 80
elb_health_check_protocol: http
elb_protocol: http
elb_load_balancer_port: 80
elb_instance_listener_port: 80
