---
- name: set up app variables
  include_vars: "{{ playbook_dir }}/roles/{{ app_name }}/vars/main.yml"

- name: setup the amazon region variables
  set_fact:
    regions:
      ap-southeast-2:
        zone: "{{ build_zone }}"
        keypair: "{{ keypair }}"
        vpc_subnet_id: "{{ build_subnet }}"
        group_id: "{{ build_security_group }}"
    volumes:
        - device_name: "{{ device_name }}"
          device_type: "{{ device_type }}"
          volume_size: "{{ volume_size }}"
          delete_on_termination: "{{ delete_on_termination }}"

- name: Search for the latest Ubuntu 14.04 AMI
  ec2_ami_find:
    region: "{{ region }}"
    name: "ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"
    owner: 099720109477
    sort: name
    sort_order: descending
    sort_end: 1
    no_result_action: fail
  register: ami_result
  when: ami_type == "ubuntu"

- name: Search for the latest Amazon Linux AMI
  ec2_ami_find:
    region: "{{ region }}"
    name: "amzn-ami-hvm-2015.09.2.x86_64-gp2"
    owner: 137112412989
    sort: name
    sort_order: descending
    sort_end: 1
    no_result_action: fail
  register: ami_result
  when: ami_type == "amazonlinux"

- name: Launch new instance
  ec2:
    region: "{{ region }}"
    keypair: "{{ keypair }}"
    zone: "{{ build_zone }}"
    vpc_subnet_id: "{{ build_subnet }}"
    group_id: "{{ build_security_group }}"
    image: "{{ ami_result.results[0].ami_id }}"
    instance_type: "{{ build_instance_type }}"
    instance_tags:
      Name: "{{ name }}"
    volumes: "{{ volumes }}"
    wait: yes
  register: ec2

- name: Add new instances to host group
  add_host:
    name: "{{ item.private_ip }}"
    groups: "{{ name }}"
    ec2_id: "{{ item.id }}"
  with_items: ec2.instances

- name: Wait for instance to boot
  wait_for:
    host: "{{ item.private_ip }}"
    port: 22
    delay: 30
    timeout: 300
    state: started
  with_items: ec2.instances
