---
- name: set up app variables
  include_vars: "{{ playbook_dir }}/roles/{{ app_name }}/vars/main.yml"
  
- name: Terminate old instance(s)
  ec2:
    instance_ids: "{{ ec2_id }}"
    region: "{{ region }}"
    state: absent
    wait: yes
