---
- lc_find:
    region: "{{ region }}"
    name_regex: "{{ app }}-.*"
    sort: yes
    sort_end: -3
  register: old_lc_result

- ec2_lc:
    region: "{{ region }}"
    name: "{{ item.name }}"
    state: absent
  with_items: old_lc_result.results
  ignore_errors: yes
