---
- name: set up app variables
  include_vars: "{{ playbook_dir }}/roles/{{ app_name }}/vars/{{ target_env }}-vars.yml"

- name: set up global variables
  include_vars: "{{ playbook_dir }}/roles/{{ app_name }}/vars/main.yml"

- name: Create AMI
  ec2_ami:
    region: "{{ region }}"
    instance_id: "{{ ec2_id }}"
    name: "{{ target_env }}-{{ app_name }}-{{ ansible_date_time.iso8601 | regex_replace('[^a-zA-Z0-9]', '-') }}"
    wait: yes
    state: present
  register: ami
