---
- hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - role: aws-launch
      name: "{{ app_name }}_ami_build"

- hosts: "{{ app_name }}_ami_build"
  remote_user: "{{ remote_user }}"
  vars:
    environment: "{{ target_env }}"
  roles:
    - "{{ app_name }}"


- hosts: "{{ app_name }}_ami_build"
  connection: local
  gather_facts: yes
  roles:
    - aws-ami-build
    - aws-launchconfig-build
    - aws-loadbalancer-build
    - aws-autoscaling-build

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - aws-launchconfig-cleanup
    - aws-ami-cleanup

- name: Find existing instance(s)
  hosts: "tag_Name_{{ app_name }}_ami_build"
  gather_facts: false
  tags: find
  tasks:
    - name: Add to old_ami_build group
      group_by:
        key: old_ami_build

- hosts: old_ami_build
  connection: local
  gather_facts: no
  roles:
    - aws-ami-terminate
