---
- name: setup variables for logstash installation
  set_fact:
    elasticsearch_host: search-prod-simple-logstash-fzwbnrdb4thfyrfalfrosggtqa.ap-southeast-2.es.amazonaws.com
    elasticsearch_port: 80

- name: setup cloudwatch custom scripts
  include: cloudwatch.yml

- name: install java for running logstash
  apt: name=openjdk-7-jre-headless state=present
  sudo: true

- name: add public signing key for logstash
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present
  sudo: true

- name: add logstash repository definition
  apt_repository:
    repo: deb http://packages.elastic.co/logstash/2.1/debian stable main
    state: present
  sudo: true

- name: install logstash
  apt: name=logstash state=present
  sudo: true

- name: setup logstash config
  template:
    src: logstash-simple-log.conf.j2
    dest: "/etc/logstash/conf.d/simple-log.conf"
    mode: 0644
  sudo: true

- name: restart logstash service
  service: name=logstash state=restarted
  sudo: true
