---
- name: ensure IIS and ASP.NET are installed
  win_feature:
    name: AS-Web-Support

- name: ensure application dir exists
  win_file:
    path: c:\inetpub\helloworld
    state: directory

- name: ensure default.aspx is present
  win_copy:
    src: default.aspx
    dest: c:\inetpub\helloworld\default.aspx

- name: ensure that the helloworld web application exists
  win_iis_webapplication:
    name: helloworld
    physical_path: c:\inetpub\helloworld
    site: Default Web Site

- name: ensure that application responds properly
  uri:
    url: http://{{ ansible_ssh_host}}/helloworld
    return_content: yes
  register: uri_out
  delegate_to: localhost
  until: uri_out.content | search("Hello from")
  retries: 3

- debug:
    msg: web application is available at "www.{{ jira_item }}-{{ target_env }}.{{ domain }}/helloworld"
